### ISSUE TITLE
希望兄弟能继续维护这个脚本，能不能WireGuard解锁，能任意端口 Origin Rules 回源？

### ISSUE THREAD

**Issue by sw19999** [TheyCallMeSecond/sing-box-manager#2]
安装WireGuard解锁，但是不能任意端口回源，兄弟看看能不能修改一下，能任意端口 Origin Rules 回源。

或者说一下如何修改？ 谢谢！

这个脚本是可以的，但是不如你这个可以每个协议自定义端口：https://github.com/fscarmen/sing-box

**Comment by TheyCallMeSecond** [comment]
只需使用以下命令打开配置文件：
```
nano /usr/local/etc/sing-box/config.json
```
并删除您想要的任何规则并重新启动服务
![240123_16h00m57s_screenshot](https://github.com/TheyCallMeSecond/sing-box-manager/assets/73380906/6da54da0-3715-44b5-978f-3cd727e84fd9)

**Comment by sw19999** [comment]
感谢兄弟回复。

修改了也不行，也许我改不对，我的想法是vmess ws可以自定义一个端口。用Origin Rules 回源，其它的协议不受影响。直连。另外再反馈一下问题，先用脚本安装vmess ws协议，用非443端口，然后安装WireGuard，随便选择一个解锁，然后选 1). warp-IPv4，这个端口就连不上了

{
  "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },
  "route": {
    "rules": [
      {
        "outbound": "warp-IPv4-out",
        "rule_set": [
        ]
      },
      {
        "inbound": [
          "l8szxblu-in"
        ],
        "outbound": "direct"
      }
    ],

**Comment by TheyCallMeSecond** [comment]
使用它，您可以在您想要的协议上启用/禁用扭曲 :
https://github.com/TheyCallMeSecond/config-examples

**Comment by papampi** [comment]
> Using it you can enable/disable twisted on the protocol you want: https://github.com/TheyCallMeSecond/config-examples

@TheyCallMeSecond 
I can use [sci](https://github.com/TheyCallMeSecond/config-examples) script on server that has sing-box-manager installed on?
They don't conflict?

**Comment by TheyCallMeSecond** [comment]
yes you can

**Comment by papampi** [comment]
> yes you can

But we can't manage sing-box-manager configs with sci? correct?
I tried and sci shows no config installed, they have different paths and services?

**Comment by TheyCallMeSecond** [comment]
no you cant manage another script with this script
